apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy-prod
  name: nginx-deploy-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy-prod
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deploy-prod
    spec:
      containers:
      - image: nginx
        name: nginx