apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      lob: auto
  template:
    metadata:
      labels:
        app: nginx
        lob: auto