apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-prod-kp
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx-prod-kp
  template:
    metadata:
      labels:
        app: nginx-prod-kp