apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
    lob: auto
    env: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-deploy
      lob: auto
      env: prod
  template:
    metadata:
      labels:
        app: nginx-deploy
        lob: auto
        env: prod