apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      lob: auto
      env: prod
  template:
    metadata:
      labels:
        app: nginx
        lob: auto
        env: prod