apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod