apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    lob: auto
    env: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-deploy
  template:
  metadata:
    labels:
      app: nginx-deploy