apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/nginx
labels:
  - pairs:
      env: dev
      lob: auto 
      app: nginx
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default
#patches:
#  - path: nginx-dev.yaml
#    target:
#      kind: Deployment