apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        app: nginx-dev
