---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-prod
  namespace: flux-system
spec:
  interval: 0m30s
  path: ./apps/kustomize-prod
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: gitops-flux-demo
  targetNamespace: prod
  timeout: 3m0s
  wait: true
