apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy
      lob: none
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deploy
        lob: none
    spec:
      containers:
      - image: nginx
        name: nginx