apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
    lob: none
    env: none
  name: nginx-deploy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: nginx
        name: nginx